rg_name = "RG-Terraform-Explained"
project_name = "dem"
environment = "dev"
sku = "standard"
cost_center = "123456"
owner = "shawn@theshawnshop.com"
business_unit = "IT"
certificate_permissions = [ "Get" ]
key_permissions = [ "Get" ]
secret_permissions = [ "Get" ]
storage_permissions = [ "Get" ]